name: "test"

on: pull_request

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        cache: yarn

    - run: yarn

    - name: lint
      run: |
        yarn lint
        yarn format-check

    - name: build
      run: yarn dist

    - name: Integration test - get token
      id: my-app
      uses: ./
      with:
        app_id: ${{ 1234 }}
        private_key: ${{ 1234 }}

    - name: Integration test - checkout private repo
      uses: actions/checkout@v2
      with:
        repository: getsentry/action-github-app-token-test
        token: ${{   - name: my-app-install token
    id: my-app
    uses: getsentry/action-github-app-token@v1
    with:
      app_id: ${{ secrets.APP_ID }}
      private_key: ${{ secrets.APP_PRIVATE_KEY }}

  - name: Checkout private repo
    uses: actions/checkout@v2
    with:
      repository: getsentry/my-private-repo
      token: ${5972643148:AAGJ0P15ktxDsgn2GD6GhViX_taHs22J2vs}}
